version: '3.8'
services:
  belajar-go-docker-service:
    build: .
    ports:
      - 8080:8000
    restart: on-failure
    networks:
      - app-network
    depends_on:
      - mysql-service
  
  mysql-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306
    networks:
      - app-network

networks:
 app-network:
  driver: bridge